fantasticParakeet/fantasticParakeet/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using fantasticParakeet.Areas.HelpPage.Models;

namespace fantasticParakeet.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

fantasticParakeet/fantasticParakeet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace fantasticParakeet.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

fantasticParakeet/fantasticParakeet/Views/Home/Index.cshtml
@{
    Layout = null;
    Response.Headers["X-UA-Compatible"] = "IE=10";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div data-bind="visible: loading">Loading...</div>
    <div style="display: none" data-bind="visible: true" class="container body-content">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container"> 
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p class="navbar-brand" data-bind="if: !loggedIn()">Application Name</p>
                    <a href="#" class="navbar-brand" data-bind="if: loggedIn, click: navigateToHome">Application Name</a>
                </div>
                <div data-bind="if: loggedIn" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#" data-bind="click: navigateToHome">Home</a></li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" data-bind="with: user">
                        <li>
                            <span class="navbar-text nofloat">Hello, <a href="#" class="navbar-link" data-bind="text: name, click: manage"></a>!</span>
                        </li>
                        <li><a href="#" data-bind="click: logOff">Log off</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div data-bind="foreach: errors" class="padding-error">
            <p class="text-danger" data-bind="text: $data"></p>
        </div>
        @Html.Partial("_Home")
        @Html.Partial("_Login")
        @Html.Partial("_Register")
        @Html.Partial("_RegisterExternal")
        @Html.Partial("_Manage")
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/app")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

fantasticParakeet/fantasticParakeet/Views/Home/_Home.cshtml
<!-- ko with: home -->
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a> </p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET Single Page Application (SPA) helps you build applications that include significant client-side interactions using HTML, CSS, and JavaScript.
            It's now easier than ever before to getting started writing highly interactive web applications.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=273732">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
<!-- /ko -->

fantasticParakeet/fantasticParakeet/Views/Home/_Login.cshtml
<!-- ko with: login -->
<h2>Log in</h2>

<div class="row">
    <section class="col-md-8">
        <form class="form-horizontal" role="form">
            <h4>Use a local account to log in.</h4>
            <hr />
            <ul class="text-danger" data-bind="foreach: errors">
                <li data-bind="text: $data"></li>
            </ul>
            <div class="form-group">
                <label for="LoginUserName" class="col-md-2 control-label">User name</label>
                <div class="col-md-10">
                    <input type="text" id="LoginUserName" class="form-control" data-bind="value: userName, hasFocus: true" />
                </div>
            </div>
            <div class="form-group">
                <label for="LoginPassword" class="col-md-2 control-label">Password</label>
                <div class="col-md-10">
                    <input type="password" id="LoginPassword" class="form-control" data-bind="value: password" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        <input type="checkbox" id="LoginRememberMe" data-bind="checked: rememberMe" />
                        <label for="LoginRememberMe">Remember me?</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default" data-bind="click: login, disable: loggingIn">Log in</button>
                </div>
            </div>
            <p><a href="#" data-bind="click: register">Register</a> if you don't have a local account.</p>

        </form>
    </section>
    <section class="col-md-4">
        <h4>Use another service to login.</h4>
        <hr />
        <div data-bind="visible: loadingExternalLogin">Loading...</div>
        <div data-bind="visible: !loadingExternalLogin()">
            <div data-bind="visible: !hasExternalLogin()">
                <p>
                    There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=313242">this article</a>
                    for details on setting up this ASP.NET application to support logging in via external services.
                </p>
            </div>
            <form class="form-horizontal" role="form" data-bind="visible: hasExternalLogin">
                <p data-bind="foreach: externalLoginProviders">
                    <button type="submit" class="btn btn-default" data-bind="text: name, attr: { title: 'Log in using your ' + name() + ' account' }, click: login"></button>
                </p>
            </form>
        </div>
    </section>
</div>
<!-- /ko -->

fantasticParakeet/fantasticParakeet/Views/Home/_Manage.cshtml
<!-- ko with: manage -->
<div data-bind="visible: loading">Loading...</div>
<div data-bind="visible: !loading()">
    <p class="text-success" data-bind="text: message"></p>
    <h2>Manage Account</h2>
    <section>
        <div data-bind="with: changePassword">
            <p class="text-info">You're logged in as <strong data-bind="text: name"></strong>.</p>
            <form class="form-horizontal" role="form">
                <h4>Change your password</h4>
                <hr />
                <ul class="text-danger" data-bind="foreach: errors">
                    <li data-bind="text: $data"></li>
                </ul>
                <div class="form-group">
                    <label for="ChangePasswordOldPassword" class="col-md-2 control-label">Old password</label>
                    <div class="col-md-10">
                        <input type="password" id="ChangePasswordOldPassword" class="form-control" data-bind="value: oldPassword" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="ChangePasswordNewPassword" class="col-md-2 control-label">New password</label>
                    <div class="col-md-10">
                        <input type="password" id="ChangePasswordNewPassword" class="form-control" data-bind="value: newPassword" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="ChangePasswordConfirmPassword" class="col-md-2 control-label">Confirm new password</label>
                    <div class="col-md-10">
                        <input type="password" id="ChangePasswordConfirmPassword" class="form-control" data-bind="value: confirmPassword" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default" data-bind="click: change, disable: changing">Change password</button>
                    </div>
                </div>
            </form>
        </div>
        <div data-bind="with: setPassword">
            <p>You do not have a local username/password for this site. Add a local account so you can log in without an external login.</p>
            <form class="form-horizontal" role="form">
                <h4>Create Local Login</h4>
                <hr />
                <ul class="text-danger" data-bind="foreach: errors">
                    <li data-bind="text: $data"></li>
                </ul>
                <div class="form-group">
                    <label for="SetPasswordNewPassword" class="col-md-2 control-label">New password</label>
                    <div class="col-md-10">
                        <input type="password" id="SetPasswordNewPassword" class="form-control" data-bind="value: newPassword" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="SetPasswordConfirmPassword" class="col-md-2 control-label">Confirm new password</label>
                    <div class="col-md-10">
                        <input type="password" id="SetPasswordConfirmPassword" class="form-control" data-bind="value: confirmPassword" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default" data-bind="click: set, disable: setting">Set password</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <ul class="text-danger" data-bind="foreach: errors">
            <li data-bind="text: $data"></li>
        </ul>
        <div data-bind="if: logins().length > 0">
            <h4>Registered logins</h4>
            <table class="table">
                <tbody data-bind="foreach: logins">
                    <tr>
                        <td data-bind="text: loginProvider"></td>
                        <td>
                            <div data-bind="if: $parent.canRemoveLogin">
                                <form>
                                    <div>
                                        <button type="submit" class="btn btn-default" data-bind="attr: { title: 'Remove this ' + loginProvider() + ' credential from your account' }, click: remove, disable: removing">Remove</button>
                                    </div>
                                </form>
                            </div>
                            <span data-bind="if: !$parent.canRemoveLogin()">&nbsp;</span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2>Add an external login</h2>
        <div data-bind="visible: !hasExternalLogin()">
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=313242">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
        <form class="form-horizontal" role="form" data-bind="visible: hasExternalLogin">
            <h4>Use another service to log in.</h4>
            <hr />
            <p data-bind="foreach: externalLoginProviders">
                <button type="submit" class="btn btn-default" data-bind="text: name, attr: { title: 'Log in using your ' + name() + ' account' }, click: login"></button>
            </p>
        </form>
    </section>
</div>
<!-- /ko -->

fantasticParakeet/fantasticParakeet/Views/Home/_Register.cshtml
<!-- ko with: register -->
<h2>Register</h2>
<form class="form-horizontal" role="form">
    <h4>Create a new account.</h4>
    <hr />
    <ul class="text-danger" data-bind="foreach: errors">
        <li data-bind="text: $data"></li>
    </ul>
    <div class="form-group">
        <label for="RegisterUserName" class="col-md-2 control-label">User name</label>
        <div class="col-md-10">
            <input type="text" id="RegisterUserName" class="form-control" data-bind="value: userName, hasFocus: true" />
        </div>
    </div>
    <div class="form-group">
        <label for="RegisterPassword" class="col-md-2 control-label">Password</label>
        <div class="col-md-10">
            <input type="password" id="RegisterPassword" class="form-control" data-bind="value: password" />
        </div>
    </div>
    <div class="form-group">
        <label for="RegisterConfirmPassword" class="col-md-2 control-label">Confirm password</label>
        <div class="col-md-10">
            <input type="password" id="RegisterConfirmPassword" class="form-control" data-bind="value: confirmPassword" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default" data-bind="click: register, disable: registering">Register</button>
        </div>
    </div>
    <p><a href="#" data-bind="click: login">Log in</a> if you already have a local account.</p>
</form>
<!-- /ko -->

fantasticParakeet/fantasticParakeet/Views/Home/_RegisterExternal.cshtml
<!-- ko with: registerExternal -->
<h2>Register</h2>
<form class="form-horizontal" role="form">
    <h4 data-bind="text: 'Associate your ' + loginProvider() + ' account.'"></h4>
    <hr />
    <p class="text-success">
        You've successfully authenticated with <strong data-bind="text: loginProvider"></strong>.
            Please enter a user name for this site below and click the Register button to finish logging in.
    </p>
    <ul class="text-danger" data-bind="foreach: errors">
        <li data-bind="text: $data"></li>
    </ul>
    <div class="form-group">
        <label for="RegisterExternalUserName" class="col-md-2 control-label">User name</label>
        <div class="col-md-10">
            <input type="text" id="RegisterExternalUserName" class="form-control" data-bind="value: userName, hasFocus: true" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default" data-bind="click: register, disable: registering">Sign up</button>
        </div>
    </div>
</form>
<!-- /ko -->